[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gputil>=1.4.0",
    "pillow>=12.0.0",
    "psutil>=7.1.3",
    "pystray>=0.19.5",
    "pyadl>=0.1",
]
